### ISSUE TITLE
Gatsby preview not showing in strapi settings

### ISSUE THREAD

**Issue by sikander804** [strapi/strapi-plugin-gatsby-preview#4]
Hi , i have installed `strapi-plugin-gatsby-preview ` but in strapi admin panel -> setting tab i cannot see it below is the screen shot.

![Image 2](https://user-images.githubusercontent.com/60669129/177758952-d343067f-89b1-45d4-9de3-72b071b83068.png)

and in plugins tab its showing that it is installed

![Image 4](https://user-images.githubusercontent.com/60669129/177759062-43d15128-3cf3-43b4-8c97-1f7ebb6f881f.png)

i am using it locally with gatsby
please help me out

**Comment by jmdrawneek** [comment]
@sikander804 Have you rebuilt the strapi admin UI?

**Comment by kuczaQ** [comment]
Running `npm run build` indeed solved the problem for me!

**Comment by remidej** [comment]
Yes either yarn build or run the admin in watch mode with --watch-admin flag
