### ISSUE TITLE
Rich text updates within Strapi break gatsby preview.

### ISSUE THREAD

**Issue by SeanDYoko** [strapi/strapi-plugin-gatsby-preview#6]
When a rich text field is updated, the rich text field returns a null value upon content sync refresh.

## Steps to Replicate
1. make a change within strapi on a rich text field
2. save the page
3. open the content sync preview
4. observe preview crash due to null being returned in the rich text place. 

## Work around for now
I was able to work around this problem by adding an empty component to the page, saving to update the preview and then deleting the component again and saving. It's a little tedious, but it works for now.
Can anyone else replicate this besides me? 

## Screen Shots
Initial Working rich text from first publish
![image](https://user-images.githubusercontent.com/53785593/235973616-cb1ede1f-7146-4f1e-ac8c-31644628ce1d.png)

Modified in Strapi as follows:
![image](https://user-images.githubusercontent.com/53785593/235974004-74a96936-d415-4a37-8db6-42bb7ab4ab84.png)

My expectation was for the preview to update, Here is the result
![image](https://user-images.githubusercontent.com/53785593/235974263-e44c9bb9-8c14-478d-a3d5-769b02a37928.png)

When I click view error logs I get this:
![image](https://user-images.githubusercontent.com/53785593/235974379-4cbe3031-60ee-4369-a50f-b7df7196a9f6.png)

all successful. Then when I navigate to the preview I see this:
![image](https://user-images.githubusercontent.com/53785593/235974658-9de542ad-3fb1-4003-811d-24d2880c4808.png)

We have a check that makes sure if there is a null returned, the rich text is not rendered because it was breaking previews all together.
If anyone has any suggestions, please share, I have not been able to locate a prime solution to this.

**Comment by SeanDYoko** [comment]
@soupette I was wondering if you could help me clarify an issue I raised a month ago. Unfortunately, I haven't received any updates on it yet.

**Comment by soupette** [comment]
Hello @SeanDYoko 👋 

It seems that this repository is not really maintained anymore maybe you should reach out to @joshuaellis and @gu-stav they might be able to unblock you or give you an update regarding the status of the source plugin.

**Comment by remidej** [comment]
Hello! I think the issue is likely coming from gatsby-source-strapi, not the Gatsby preview plugin. It looks like [this one](https://github.com/gatsby-uc/plugins/issues/338) that we've had in the past. Could you let us know which version of gatsby-source-strapi you're using? The current recommended one is 3.2.0

**Comment by SeanDYoko** [comment]
Thank you so much for getting back to me @soupette  and @remidej. This seemed to solve my problem, we were running 2.0.0, so definitely needed an update. I will pay attention to versioning here in the future. 
Thank you for your help, again.
